//Khai báo một loạt các đối tượng compound trong hệ thống.
class compound {
  final String formula;
  final String iupacname;
  final String commonname;

  compound(this.formula, this.iupacname, this.commonname);
}

List<compound> Compounds = [
  // Aldehyde
  compound('HCHO', 'methanal', ''),
  compound('CH3CHO', 'ethanal', ''),
  compound('C2H5CHO', 'propanal', ''),
  compound('CH3CH2CH2CHO', 'butanal', ''),
  compound('CH3[CH2]3CHO', 'pentanal', ''),
  compound('(CH3)2CHCH2CHO', '3-methylbutanal', ''),
  compound('CH2=CHCHO', '2-propenal', ''),
  compound('C6H5CHO', 'phenylmethanal', ''),
  compound('CH3CH(OH)CHO', 'hydroxypropanal', ''),
  compound('CH3CHOHCHO', 'methylenepropanal', ''),
  compound('CH3CH2CH(OH)CHO', '3-hydroxybutanal', ''),
  compound('CH3CH2CH2CH2CHO', 'pentanal', ''),
  compound('(CH3)2CHCHO', 'isobutanal', ''),
  compound('CH3CH2CH2CH=CHCHO', 'pent-2-enal', ''),
  compound('C6H5CH(OH)CHO', 'benzylhydroxybenzene', ''),
  compound('CH3CH2CH2CH2CH2CHO', 'hexanal', ''),
  compound('CH3CH2CH2CH2CH2CH2CHO', 'heptanal', ''),
  compound('C6H5CH2CHO', 'benzylmethanal', ''),
  compound('CH3CH2CH2CH=CHCH2CHO', 'pent-3-enal', ''),
  compound('C6H5CH2CH=CHCHO', 'styrylmethanal', ''),
  compound('C6H5CH2CH2CH2CH2CHO', 'benzylpentanal', ''),
  compound('CH3CH2CH2CH2CH2CHO', 'hexanal', ''),
  compound('CH3CH2CH2CH2CH2CH2CHO', 'heptanal', ''),
  compound('C6H5CH2CHO', 'benzylmethanal', ''),
  compound('CH3CH2CH2CH=CHCH2CHO', 'pent-3-enal', ''),
  compound('C6H5CH2CH=CHCHO', 'styrylmethanal', ''),
  compound('C6H5CH2CH2CH2CH2CHO', 'benzylpentanal', ''),
  compound('CH3CH2CH2CH2CH2CHO', 'hexanal', ''),
  compound('CH3CH2CH2CH2CH2CH2CHO', 'heptanal', ''),
  compound('C6H5CH2CHO', 'benzylmethanal', ''),
  compound('CH3CH2CH2CH=CHCH2CHO', 'pent-3-enal', ''),
  compound('C6H5CH2CH=CHCHO', 'styrylmethanal', ''),
  compound('C6H5CH2CH2CH2CH2CHO', 'benzylpentanal', ''),
  compound('CH3CH2CH2CH2CHO', 'butylaldehyde', ''),
  compound('C6H5CH2CH2CH=CHO', 'benzyloxybutenylaldehyde', ''),
  compound('CH3CH2CH=CHCHO', 'pent-2-enal', ''),
  compound('C6H5CH2CH2CH=CHO', 'benzyloxybutenylaldehyde', ''),
  compound('C6H5CH2CH=CHO', 'styrylbenzylaldehyde', ''),
  compound('C6H5CH(OH)CHO', 'benzylhydroxybenzene', ''),
  compound('CH3CH2CH(OH)CHO', '3-hydroxybutanal', ''),
  compound('CH3CHOHCHO', 'methylenepropanal', ''),
  compound('C6H5CHO', 'phenylmethanal', ''),
  compound('CH3CH2CHO', 'ethanal', ''),
  compound('C2H5CHO', 'propanal', ''),
  compound('(CH3)2CHCHO', 'isobutanal', ''),
  compound('CH3CH2CH2CH=CHCHO', 'pent-2-enal', ''),
  compound('C6H5CH(OH)CHO', 'benzylhydroxybenzene', ''),
  compound('CH3CH2CH(OH)CHO', '3-hydroxybutanal', ''),
  compound('C6H5CHO', 'phenylmethanal', ''),
  compound('CH3CHOHCHO', 'methylenepropanal', ''),
  compound('C6H5CH2CHO', 'benzylmethanal', ''),
  compound('C6H5CH2CH2CHO', 'benzyloxybutanal', ''),
  compound('CH3CH(OH)CHO', 'hydroxypropanal', ''),
  compound('CH3CH2CH=CHO', 'but-2-enal', ''),
  compound('C6H5CH2CH2CH2CHO', 'benzylbutanal', ''),
  compound('CH3CH2CH2CH2CH2CH2CH2CHO', 'octanal', ''),
  compound('C6H5CH2CH=CHCH2CHO', 'styrylpent-2-enal', ''),
  compound('C6H5CH2CH=CHCH2CHO', 'styrylpent-3-enal', ''),
  compound('C6H5CH2CH2CH=CHCH2CHO', 'benzyloxyhex-2-enal', ''),
  compound('CH3CH2CH2CHO', 'butyraldehyde', ''),
  compound('C6H5CH2CH2CH2CH2CH2CHO', 'hexylbenzylaldehyde', ''),
  compound('C6H5CH2CH2CH=CHCHO', 'benzyloxyhex-2-enal', ''),
  compound('C6H5CH2CH2CH=CHCHO', 'benzyloxyhex-3-enal', ''),
  compound('CH3CH2CH2CH2CH2CHO', 'pentylaldehyde', ''),
  compound('C6H5CH2CH2CH=CHO', 'styrylbenzylaldehyde', ''),
  compound('C6H5CH2CH2CH=CHO', 'styrylbenzyloxyaldehyde', ''),
  compound('CH3CH2CH2CH2CHO', 'butylaldehyde', ''),
  compound('C6H5CH2CH2CH2CH2CH2CH2CHO', 'octylbenzylaldehyde', ''),
  compound('C6H5CH2CH2CH2CH2CHO', 'hexylbenzylaldehyde', ''),
  compound('C6H5CH2CH2CH=CHCH2CHO', 'styrylhex-2-enal', ''),
  compound('C6H5CH2CH=CHCHO', 'styrylbenzylaldehyde', ''),
  compound('CH3CH2CH=CHCHO', 'but-2-enal', ''),
  compound('C6H5CH2CHO', 'benzylmethanal', ''),
  compound('CH3CH2CH2CHO', 'butanal', ''),
  compound('(CH3)2CHCHO', 'isobutanal', ''),
  compound('CH3CH2CH2CH=CHCHO', 'pent-2-enal', ''),
  compound('C6H5CH(OH)CHO', 'benzylhydroxybenzene', ''),
  compound('CH3CH2CH(OH)CHO', '3-hydroxybutanal', ''),
  compound('C6H5CHO', 'phenylmethanal', ''),
  compound('CH3CHOHCHO', 'methylenepropanal', ''),
  compound('C6H5CH2CHO', 'benzylmethanal', ''),
  compound('C6H5CH2CH2CHO', 'benzyloxybutanal', ''),
  compound('CH3CH(OH)CHO', 'hydroxypropanal', ''),
  // Ketone
  compound('CH3COCH3', 'propanone', ''),
  compound('CH3COCH2CH3', 'butanone', ''),
  compound('C2H5COC2H5', 'pentan-2-one', ''),
  compound('CH3COCH=CH2', 'but-3-en-2-one', ''),
  compound('C6H5COCH3', '1-phenylethan-1-one', ''),
  compound('C6H5CH2COCH3', '1-phenylpropan-2-one', ''),
  compound('C6H5COC6H5', 'diphenylmethanone', ''),
  compound('CH3COCH2CH2CH3', 'pentan-3-one', ''),
  compound('CH3COCH2CH2CH2CH3', 'hexan-3-one', ''),
  compound('C6H5COCH2CH3', 'acetophenone', ''),
  compound('C6H5COCH2CH2CH3', 'methylacetophenone', ''),
  compound('C6H5COCH2CH2CH2CH3', 'ethylacetophenone', ''),
  compound('C6H5COCH2CH2CH2CH2CH3', 'butylacetophenone', ''),
  compound('C6H5COCH=CH2', 'styrylacetophenone', ''),
  compound('C6H5COCH2CH=CH2', 'vinylacetophenone', ''),
  compound('C6H5COCH=CHO', 'styrylbenzylketone', ''),
  compound('C6H5COCH=CHCHO', 'styrylbenzylacetaldehyde', ''),
  compound('C6H5COCH2CHO', 'benzylmethylketone', ''),
  compound('C6H5COCH2CH2CHO', 'benzylmethylpropylketone', ''),
  compound('C6H5COCH2CH2CH2CHO', 'benzylmethylbutylketone', ''),
  compound('C6H5COCH2CH2CH2CH2CHO', 'benzylmethylpentylketone', ''),
  compound('C6H5COCH2CH=CHCHO', 'vinylbenzylmethylketone', ''),
  compound('C6H5COCH2CH=CHCH2CHO', 'vinylbenzylmethylpropylketone', ''),
  compound('C6H5COCH=CHCHO', 'styrylbenzylmethylketone', ''),
  compound('C6H5COCH2CH=CHO', 'vinylbenzylmethylacetaldehyde', ''),
  compound('C6H5COCH2CH2CH=CHO', 'benzylmethylpropylacetaldehyde', ''),
  compound('C6H5COCH2CH2CH2CH=CHO', 'benzylmethylbutylacetaldehyde', ''),
  compound('CH3COCH2CH2CH3', 'pentan-3-one', ''),
  compound('CH3COCH2CH2CH2CH3', 'hexan-3-one', ''),
  compound('C6H5COCH2CH3', 'acetophenone', ''),
  compound('C6H5COCH2CH2CH3', 'methylacetophenone', ''),
  compound('C6H5COCH2CH2CH2CH3', 'ethylacetophenone', ''),
  compound('C6H5COCH2CH2CH2CH2CH3', 'butylacetophenone', ''),
  compound('C6H5COCH=CH2', 'styrylacetophenone', ''),
  compound('C6H5COCH2CH=CH2', 'vinylacetophenone', ''),
  compound('C6H5COCH=CHO', 'styrylbenzylketone', ''),
  compound('C6H5COCH=CHCHO', 'styrylbenzylacetaldehyde', ''),
  compound('C6H5COCH2CHO', 'benzylmethylketone', ''),
  compound('C6H5COCH2CH2CHO', 'benzylmethylpropylketone', ''),
  compound('C6H5COCH2CH2CH2CH2CH3', 'benzylmethylbutylketone', ''),
  compound('C6H5COCH2CH2CH2CH2CH2CHO', 'benzylmethylbutylacetaldehyde', ''),
  compound('C6H5COCH2CH=CHCHO', 'vinylbenzylmethylpropylketone', ''),
  compound('C6H5COCH2CH=CHCH2CHO', 'vinylbenzylmethylpropylacetaldehyde', ''),
  compound('C6H5COCH2CH2CH=CHO', 'benzylmethylpropylacetaldehyde', ''),
  compound('C6H5COCH2CH2CH2CH2CH2CH2CHO', 'benzylmethylbutylacetaldehyde', ''),
  compound('C6H5COCH2CH=CH2', 'vinylbenzylmethylpropylketone', ''),
  compound('C6H5COCH2CH=CHCH2CHO', 'vinylbenzylmethylpropylacetaldehyde', ''),
  compound('C6H5COCH=CHO', 'styrylbenzylketone', ''),
  compound('C6H5COCH=CHCHO', 'styrylbenzylacetaldehyde', ''),
  compound('C6H5COCH2CH=CHO', 'vinylbenzylmethylpropylacetaldehyde', ''),
  compound('C6H5COCH2CH=CHCH2CHO', 'vinylbenzylmethylpropylacetaldehyde', ''),
  compound('C6H5COCH2CH2CH=CHO', 'benzylmethylpropylacetaldehyde', ''),
  compound('C6H5COCH2CH2CH2CH2CH2CH2CHO', 'benzylmethylbutylacetaldehyde', ''),
  compound('CH3COCH(CH3)2', 'diisopropylketone', ''),
  compound('CH3COCH(CH3)CH2CH3', 'methylisobutylketone', ''),
  compound('CH3COCH2C6H5', 'acetophenone', ''),
  compound('C6H5COCH2C6H5', 'benzylphenylketone', ''),
  compound('C6H5COCH(CH3)2', 'benzylisopropylketone', ''),
  compound('C6H5COCH2CH2CH3', 'benzyldiethylketone', ''),
  compound('C6H5COCH2CH2CH(CH3)2', 'benzyldiisopropylketone', ''),
  compound('C6H5COCH(CH3)CH2CH3', 'benzylmethylisobutylketone', ''),
  compound('CH3COCH(CH3)2', 'diisopropylketone', ''),
  compound('CH3COCH(CH3)CH2CH3', 'methylisobutylketone', ''),
  compound('CH3COCH2C6H5', 'acetophenone', ''),
  compound('C6H5COCH2C6H5', 'benzylphenylketone', ''),
  compound('C6H5COCH(CH3)2', 'benzylisopropylketone', ''),
  compound('C6H5COCH2CH2CH3', 'benzyldiethylketone', ''),
  compound('C6H5COCH2CH2CH(CH3)2', 'benzyldiisopropylketone', ''),
  compound('C6H5COCH(CH3)CH2CH3', 'benzylmethylisobutylketone', ''),
  compound('C6H5COCH(CH3)2', 'benzylmethylisopropylketone', ''),
  compound('C6H5COCH2CH(CH3)2', 'benzyldiisopropylketone', ''),
  //Compound
  
  compound('H2SO4', 'sulfuric acid', ''),
  compound('NaCl', 'sodium chloride', 'table salt'),
  compound('HNO3', 'nitric acid', ''),
  compound('C6H12O6', 'glucose', ''),
  compound('CaCO3', 'calcium carbonate', 'chalk'),
  compound('H2O', 'water', ''),
  compound('H2O2', 'hydrogen peroxide', ''),
  compound('H2S', 'hydrogen sulfide', ''),
  compound('H3PO4', 'phosphoric acid', ''),
  compound('HBr', 'hydrogen bromide', ''),
  compound('HCl', 'hydrogen chloride', ''),
  compound('HF', 'hydrogen fluoride', ''),
  compound('H2SO3', 'sulfurous acid', ''),
  compound('HNO2', 'nitrous acid', ''),
  compound('H2Se', 'hydrogen selenide', ''),
  compound('HKO', 'hydrogen potassium oxide', ''),
  compound('H2KO2', 'potassium hydroxide', ''),
  compound('HK2O2', 'potassium superoxide', ''),
  compound('HKO3', 'potassium hydrogen carbonate', ''),
  compound('H2O2K2', 'potassium peroxide', ''),
  compound('HK2O4', 'potassium metaperiodate', ''),
  compound('HKO4', 'potassium peroxomonosulfate', ''),
  compound('H2KO5', 'potassium peroxodisulfate', ''),
  compound('HKO6', 'potassium peroxomonophosphate', ''),
  compound('H3KO6', 'tripotassium monoperoxophosphate', ''),
  compound('HKO7', 'potassium peroxotriphosphate', ''),
  compound('H2KO8', 'potassium peroxotetrathiophosphate', ''),
  compound('H3KO8', 'tripotassium peroxotetrathiophosphate', ''),
  compound('HKO9', 'potassium peroxopentathiophosphate', ''),
  compound('H2KO10', 'potassium peroxodithiophosphate', ''),
  //Alcohol
  compound('CH30H', 'methanol', ''),
  compound('CH3CH2OH', 'ethanol', ''),
  compound('CH3CH2CH2OH', '1-Propanol', ''),
  compound('CH3CH(OH)CH3', ' 2-propanol', ''),
  compound('CH2=CHCH2OH', 'prop-2-en-1-ol', ''),
  compound('CH3CH2CH2CH2OH', '1-BUTANOL', ''),
  compound('CH3CH2CH2CH2CH2OH', '1-Pentanol', ''),
  compound('HOCH2CH2OH', 'Ethane-1,2-diol', ''),
  compound('HOCH2CH(OH)CH2OH', 'Propan-1,2,3-triol', ''),
  //Hydrocarbon thơm
  compound('C6H6', 'benzene', ''),
  compound('C7H8', 'methylbenzene', ''),
  compound('C6H6CH3', 'methylbenzen', ''),
  compound('C6H5CH2CH3', 'ethylbenzene', ''),
  compound('C8H10', '1,2-dimethybenzene', ''),
  compound('C8H10', '1,3-dimethybenzene', ''),
  compound('C8H10', '1,4-dimethybenzene', ''),
  //Alkene, alkyne
  compound('CH2=CH2', 'ethen', ''),
  compound('CH2=CHCH3', 'propene', ''),
  compound('CH2=CHCH2CH3', 'but-1-ên', ''),
  compound('CH3=C(CH3)2', '2-methylpropene', ''),
  compound('CH2=CH[CH2]2CH3', 'pent-1-ene', ''),
  compound('CH≡CH', 'ethyne', ''),
  compound('CH≡CCH3', 'propyne', ''),
  compound('CH≡CCH2CH3', 'but-1-yne', ''),
  compound('CH3≡CCH3', 'but-2-yne', ''),
  compound('CH≡C[CH2]2CH3', 'pent-1-yne', ''),
  //Carborxylic
  compound('HCOOH', 'methanoic', ''),
  compound('CH3COOH', 'ethanoic acid', ''),
  compound('CH3CH2COOH', 'propanoic acid', ''),
  compound('CH3CH2CH2COOH', 'butanoic acid', ''),
  compound('CH3CH2CH2CH2COOH', 'pentanoic acid', ''),
  compound('CH2=CH-COOH', 'propenoic acid', ''),
  compound('CH2=C(CH3)-COOH', '2-methylpropenoic acid', ''),
  compound('HOOC-COOH', 'ethanedioic acid', 'oxalic acid'),
  compound('HOOC-CH2-COOH', 'propane-1,3-dioic acid', 'malonic acid'),
  compound('C6H5-COOH', 'benzoic acid', 'benzoic acid'),
  compound('CH3[CH2]14COOH', 'hexadecanoic acid', 'palmitic acid'),
  compound('CH3[CH2]16COOH', 'octadecanoic acid', 'stearic acid'),

  //Cacbonhidrat
  compound('C12H22O11', 'Saccharose', ''),
  compound('C6H12O6', 'Fructose', ''),
  compound('C6H14O6', 'Sobitol', ''),
  compound('C12H22O11', 'Mantose', ''),
  compound('C6H10O5', 'Diethyl pyrocarbonate', ''),

  //hop chat vo co 

  //
];
